"""empty message

Revision ID: 53d942899dd1
Revises: 03511fa6af09
Create Date: 2022-02-08 14:59:35.125096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53d942899dd1'
down_revision = '03511fa6af09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('poke_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('abilities', sa.String(length=150), nullable=True),
    sa.Column('base_hp', sa.Integer(), nullable=True),
    sa.Column('sprite_url', sa.String(length=1500), nullable=True),
    sa.PrimaryKeyConstraint('poke_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user__pokemon',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('poke_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['poke_id'], ['pokemon.poke_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'poke_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user__pokemon')
    op.drop_table('pokemon')
    # ### end Alembic commands ###
